
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnqpgfngzmfqnmwiqtxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducXBnZm5nem1mcW5td2lxdHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTY5MTAsImV4cCI6MjA1OTQ5MjkxMH0.Ez9iP-uIqLYHmcjQ0t34uskNMvsT2tD2c3iS6U1UXJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
